window.API = window.AppConfigState?.API || '';
window.state = state;
window.localTokenGet = localTokenGet;
window.localTokenSet = localTokenSet;
window.localTokenClear = localTokenClear;
window.apiFetch = apiFetch;
window.apiPost = apiPost;
window.apiDelete = apiDelete;
window.showToast = showToast;
window.showAuthGate = showAuthGate;
window.hideAuthGate = hideAuthGate;
window.wireAuthForm = wireAuthForm;
window.navigateTo = navigateTo;
window.viewTitle = viewTitle;
window.openAuditorInNewTab = openAuditorInNewTab;
window.buildAuthHeaders = buildAuthHeaders;
window.esc = esc;
window.fmtDate = fmtDate;
window.fmtInterval = fmtInterval;
window.timeAgo = timeAgo;
window.humanChangeType = humanChangeType;
window.copyToClipboard = copyToClipboard;
window.emptyState = emptyState;
window.fmtSize = fmtSize;
window.fileIcon = fileIcon;
window.updateStatusDot = updateStatusDot;
window.loadResource = loadResource;
window.loadStats = loadStats;
window.refreshCurrentView = refreshCurrentView;
window.renderRecentChanges = renderRecentChanges;
window.startDashboard = startDashboard;
window.startPolling = startPolling;
window.startMetricsPolling = startMetricsPolling;
window.manualRefresh = manualRefresh;
window.VIEWS = window.AppConfigState?.VIEWS || [];
window.POLL_INTERVAL = window.AppConfigState?.POLL_INTERVAL || 15000;
window.POLL_FAST_ANY = window.AppConfigState?.POLL_FAST_ANY || 7000;
window.POLL_FAST_SCANS = window.AppConfigState?.POLL_FAST_SCANS || 3500;
window.triggerScan = triggerScan;
window.syncLaunchPlaceholder = syncLaunchPlaceholder;
window.updateLaunchPreview = updateLaunchPreview;
window.syncMonitorUrlPatternVisibility = syncMonitorUrlPatternVisibility;
window.quickAddUrlMonitor = quickAddUrlMonitor;
window.quickAddSubdomainMonitor = quickAddSubdomainMonitor;
window.loadKeyhacks = loadKeyhacks;
window.renderReportTemplates = renderReportTemplates;
window.wireR2BrowserOnce = wireR2BrowserOnce;
window.loadSubdomains = loadSubdomains;
window.loadDomains = loadDomains;
window.loadScans = loadScans;
window.loadMonitor = loadMonitor;
window.loadR2 = loadR2;
window.loadConfig = loadConfig;
window.loadTargetsPlatforms = loadTargetsPlatforms;
window.copyAllSubdomainsMatching = copyAllSubdomainsMatching;
window.renderDomainGrid = renderDomainGrid;
window.refreshScanDetailIfRunning = refreshScanDetailIfRunning;
window.renderScanDetailView = renderScanDetailView;
window.pathScanId = pathScanId;
window.openScanResultsPage = openScanResultsPage;
window.wireShellOnce = wireShellOnce;
window.updateClock = updateClock;
window.browseR2ForScan = browseR2ForScan;
window.deleteScansNoFindings = deleteScansNoFindings;
window.loadDomainSubdomains = loadDomainSubdomains;
window.deleteDomainRecord = deleteDomainRecord;
window.prevFilesPage = prevFilesPage;
window.nextFilesPage = nextFilesPage;
window.parseNucleiFindingLine = parseNucleiFindingLine;
window.loadScanDetailVulnerabilityInsights = loadScanDetailVulnerabilityInsights;
window.wireScanFileRows = wireScanFileRows;
window.clearScanDetailRefreshTimer = clearScanDetailRefreshTimer;

window.getModuleDisplayInfo = getModuleDisplayInfo;
window.scanNoArtifactsMessage = scanNoArtifactsMessage;
window.escAttr = escAttr;
window.getFileTypeFromName = getFileTypeFromName;
window.getFileTypeIcon = getFileTypeIcon;
window.detectModuleFromFileName = detectModuleFromFileName;
window.normalizeModuleKey = normalizeModuleKey;
window.previewDataToFlatRows = previewDataToFlatRows;
window.categorizeScanArtifactFile = categorizeScanArtifactFile;
window.filterScanFiles = filterScanFiles;
window.copyAllScanResults = copyAllScanResults;
window.getUnifiedTableColumns = getUnifiedTableColumns;
window.renderRowForUnifiedTab = renderRowForUnifiedTab;
window.renderDefaultRow = renderDefaultRow;
window.formatJSONWithHighlighting = formatJSONWithHighlighting;

window.renderResultTable = renderResultTable;
window.renderSubdomainListTable = (...args) => window.ResultTablesPage?.renderSubdomainListTable?.(...args) || '';
window.renderSubdomainObjectTable = (...args) => window.ResultTablesPage?.renderSubdomainObjectTable?.(...args) || '';
window.renderHTTPXTable = (...args) => window.ResultTablesPage?.renderHTTPXTable?.(...args) || '';
window.renderNucleiTable = (...args) => window.ResultTablesPage?.renderNucleiTable?.(...args) || '';
window.renderZeroDaysTable = (...args) => window.ResultTablesPage?.renderZeroDaysTable?.(...args) || '';
window.renderJSFindingsTable = (...args) => window.ResultTablesPage?.renderJSFindingsTable?.(...args) || '';
window.renderXSSFindingsTable = (...args) => window.ResultTablesPage?.renderXSSFindingsTable?.(...args) || '';
window.renderSQLiFindingsTable = (...args) => window.ResultTablesPage?.renderSQLiFindingsTable?.(...args) || '';
window.renderURLListTable = (...args) => window.ResultTablesPage?.renderURLListTable?.(...args) || '';
window.renderBackupFindingsTable = (...args) => window.ResultTablesPage?.renderBackupFindingsTable?.(...args) || '';
window.renderMisconfigTable = (...args) => window.ResultTablesPage?.renderMisconfigTable?.(...args) || '';
window.renderAEMTable = (...args) => window.ResultTablesPage?.renderAEMTable?.(...args) || '';
window.renderPortResultsTable = (...args) => window.ResultTablesPage?.renderPortResultsTable?.(...args) || '';
window.renderS3FindingsTable = (...args) => window.ResultTablesPage?.renderS3FindingsTable?.(...args) || '';
window.renderDNSFindingsTable = (...args) => window.ResultTablesPage?.renderDNSFindingsTable?.(...args) || '';
window.renderTechFindingsTable = (...args) => window.ResultTablesPage?.renderTechFindingsTable?.(...args) || '';
window.renderGenericJSONTable = (...args) => window.ResultTablesPage?.renderGenericJSONTable?.(...args) || '';
window.renderModuleBadge = renderModuleBadge;
window.renderCategoryBadge = renderCategoryBadge;
window.scanItemHtml = scanItemHtml;
